apiVersion: v1
kind: Pod
metadata:
  name: python3-pod
spec:
  containers:
    - name: python3-container
      image: python:3.8
      command: ["sleep", "infinity"]
      resources:
        limits:
          memory: 4Gi
          cpu: 2
        requests:
          memory: 4Gi
          cpu: 2
      volumeMounts:
        - mountPath: /data
          name: my-pvc # CHANGE THIS TO YOUR PVC
  volumes:
    - name: my-pvc # CHANGE THIS TO YOUR PVC
      persistentVolumeClaim:
        claimName: my-pvc # CHANGE THIS TO YOUR PVC
