apiVersion: v1
kind: Pod
metadata:
  name: jhurt-ubuntu
spec:
  containers:
    - name: ubuntu-container
      image: ubuntu:20.04
      imagePullPolicy: IfNotPresent
      command: ["sleep", "infinity"]
      resources:
        limits:
          memory: 4Gi
          cpu: 2
        requests:
          memory: 4Gi
          cpu: 2
      volumeMounts:
        - mountPath: /data
          name: my-pvc # CHANGE THIS TO YOUR PVC
  volumes:
    - name: my-pvc # CHANGE THIS TO YOUR PVC
      persistentVolumeClaim:
        claimName: my-pvc # CHANGE THIS TO YOUR PVC
