apiVersion: v1
kind: Pod

metadata:
  name: name-here

spec:
  containers:
    - name: mmdet
      image: image-name-here
      imagePullPolicy: IfNotPresent
      command: ["sleep", "infinity"]
      resources:
        limits:
          memory: 12Gi
          cpu: 2
          nvidia.com/gpu: 1
        requests:
          memory: 12Gi
          cpu: 2
          nvidia.com/gpu: 1
      volumeMounts:
        - mountPath: /data
          name: my-pvc
        # IMPORTANT: we need SHM for PyTorch
        - mountPath: /dev/shm
          name: dshm
  volumes:
    - name: my-pvc
      persistentVolumeClaim:
        claimName: my-pvc
    # setup shared memory as a RAM volume
    - name: dshm
      emptyDir:
        medium: Memory
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: nvidia.com/gpu.product
                operator: In
                values:
                  - NVIDIA-GeForce-RTX-3090
                  - Tesla-T4
